// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	Test
	MsgHead
	DBSetRequest
	DBSetResponse
	DBGetRequest
	DBGetResponse
	PlayerInfo
*/
package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FOO int32

const (
	FOO_X FOO = 17
)

var FOO_name = map[int32]string{
	17: "X",
}
var FOO_value = map[string]int32{
	"X": 17,
}

func (x FOO) Enum() *FOO {
	p := new(FOO)
	*p = x
	return p
}
func (x FOO) String() string {
	return proto.EnumName(FOO_name, int32(x))
}
func (x *FOO) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FOO_value, data, "FOO")
	if err != nil {
		return err
	}
	*x = FOO(value)
	return nil
}
func (FOO) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MsgId int32

const (
	MsgId_DB_SET MsgId = 0
	MsgId_DB_GET MsgId = 1
)

var MsgId_name = map[int32]string{
	0: "DB_SET",
	1: "DB_GET",
}
var MsgId_value = map[string]int32{
	"DB_SET": 0,
	"DB_GET": 1,
}

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}
func (x MsgId) String() string {
	return proto.EnumName(MsgId_name, int32(x))
}
func (x *MsgId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgId_value, data, "MsgId")
	if err != nil {
		return err
	}
	*x = MsgId(value)
	return nil
}
func (MsgId) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MsgType int32

const (
	MsgType_MSG_REQUEST  MsgType = 0
	MsgType_MSG_RESPONSE MsgType = 1
	MsgType_MSG_NOTIFY   MsgType = 2
)

var MsgType_name = map[int32]string{
	0: "MSG_REQUEST",
	1: "MSG_RESPONSE",
	2: "MSG_NOTIFY",
}
var MsgType_value = map[string]int32{
	"MSG_REQUEST":  0,
	"MSG_RESPONSE": 1,
	"MSG_NOTIFY":   2,
}

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}
func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (x *MsgType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgType_value, data, "MsgType")
	if err != nil {
		return err
	}
	*x = MsgType(value)
	return nil
}
func (MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Test struct {
	Label            *string             `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
	Type             *int32              `protobuf:"varint,2,opt,name=type,def=77" json:"type,omitempty"`
	Reps             []int64             `protobuf:"varint,3,rep,name=reps" json:"reps,omitempty"`
	Optionalgroup    *Test_OptionalGroup `protobuf:"group,4,opt,name=OptionalGroup,json=optionalgroup" json:"optionalgroup,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_Test_Type int32 = 77

func (m *Test) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *Test) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Test_Type
}

func (m *Test) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func (m *Test) GetOptionalgroup() *Test_OptionalGroup {
	if m != nil {
		return m.Optionalgroup
	}
	return nil
}

type Test_OptionalGroup struct {
	RequiredField    *string `protobuf:"bytes,5,req,name=RequiredField" json:"RequiredField,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Test_OptionalGroup) Reset()                    { *m = Test_OptionalGroup{} }
func (m *Test_OptionalGroup) String() string            { return proto.CompactTextString(m) }
func (*Test_OptionalGroup) ProtoMessage()               {}
func (*Test_OptionalGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Test_OptionalGroup) GetRequiredField() string {
	if m != nil && m.RequiredField != nil {
		return *m.RequiredField
	}
	return ""
}

type MsgHead struct {
	MsgId            *MsgId   `protobuf:"varint,1,req,name=msgId,enum=example.MsgId" json:"msgId,omitempty"`
	MsgType          *MsgType `protobuf:"varint,2,req,name=msgType,enum=example.MsgType" json:"msgType,omitempty"`
	MsgBody          []byte   `protobuf:"bytes,3,opt,name=msgBody" json:"msgBody,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MsgHead) Reset()                    { *m = MsgHead{} }
func (m *MsgHead) String() string            { return proto.CompactTextString(m) }
func (*MsgHead) ProtoMessage()               {}
func (*MsgHead) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MsgHead) GetMsgId() MsgId {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return MsgId_DB_SET
}

func (m *MsgHead) GetMsgType() MsgType {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return MsgType_MSG_REQUEST
}

func (m *MsgHead) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

type DBSetRequest struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	UidInfo          []byte  `protobuf:"bytes,2,req,name=uidInfo" json:"uidInfo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DBSetRequest) Reset()                    { *m = DBSetRequest{} }
func (m *DBSetRequest) String() string            { return proto.CompactTextString(m) }
func (*DBSetRequest) ProtoMessage()               {}
func (*DBSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DBSetRequest) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *DBSetRequest) GetUidInfo() []byte {
	if m != nil {
		return m.UidInfo
	}
	return nil
}

type DBSetResponse struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Result           *int32  `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DBSetResponse) Reset()                    { *m = DBSetResponse{} }
func (m *DBSetResponse) String() string            { return proto.CompactTextString(m) }
func (*DBSetResponse) ProtoMessage()               {}
func (*DBSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DBSetResponse) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *DBSetResponse) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type DBGetRequest struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DBGetRequest) Reset()                    { *m = DBGetRequest{} }
func (m *DBGetRequest) String() string            { return proto.CompactTextString(m) }
func (*DBGetRequest) ProtoMessage()               {}
func (*DBGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DBGetRequest) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

type DBGetResponse struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Result           *int32  `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	UidInfo          []byte  `protobuf:"bytes,3,opt,name=uidInfo" json:"uidInfo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DBGetResponse) Reset()                    { *m = DBGetResponse{} }
func (m *DBGetResponse) String() string            { return proto.CompactTextString(m) }
func (*DBGetResponse) ProtoMessage()               {}
func (*DBGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DBGetResponse) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *DBGetResponse) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *DBGetResponse) GetUidInfo() []byte {
	if m != nil {
		return m.UidInfo
	}
	return nil
}

type PlayerInfo struct {
	Uid              *uint64 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Age              *int32  `protobuf:"varint,3,req,name=age" json:"age,omitempty"`
	PhoneNum         *string `protobuf:"bytes,4,req,name=phoneNum" json:"phoneNum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerInfo) Reset()                    { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()               {}
func (*PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PlayerInfo) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *PlayerInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PlayerInfo) GetAge() int32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func (m *PlayerInfo) GetPhoneNum() string {
	if m != nil && m.PhoneNum != nil {
		return *m.PhoneNum
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "example.Test")
	proto.RegisterType((*Test_OptionalGroup)(nil), "example.Test.OptionalGroup")
	proto.RegisterType((*MsgHead)(nil), "example.MsgHead")
	proto.RegisterType((*DBSetRequest)(nil), "example.DBSetRequest")
	proto.RegisterType((*DBSetResponse)(nil), "example.DBSetResponse")
	proto.RegisterType((*DBGetRequest)(nil), "example.DBGetRequest")
	proto.RegisterType((*DBGetResponse)(nil), "example.DBGetResponse")
	proto.RegisterType((*PlayerInfo)(nil), "example.PlayerInfo")
	proto.RegisterEnum("example.FOO", FOO_name, FOO_value)
	proto.RegisterEnum("example.MsgId", MsgId_name, MsgId_value)
	proto.RegisterEnum("example.MsgType", MsgType_name, MsgType_value)
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x51, 0xc1, 0x6e, 0x9b, 0x40,
	0x10, 0x2d, 0x06, 0xe2, 0x7a, 0x8a, 0x5d, 0xba, 0xaa, 0xa2, 0x55, 0x7a, 0x28, 0x42, 0x39, 0x20,
	0x1f, 0x7c, 0x88, 0x54, 0x45, 0x8d, 0x7a, 0xa9, 0x15, 0x4c, 0x7d, 0xb0, 0x49, 0x17, 0x2a, 0xb5,
	0xa7, 0x94, 0x8a, 0x2d, 0x45, 0x02, 0x96, 0xb2, 0x20, 0xd5, 0xbf, 0xd7, 0x2f, 0xab, 0x66, 0x81,
	0x28, 0x96, 0xac, 0x1e, 0x72, 0x9b, 0xf7, 0xf6, 0xbd, 0x79, 0x33, 0x3b, 0x30, 0x2b, 0x65, 0xb6,
	0xaa, 0x1b, 0xd1, 0x0a, 0x32, 0xe5, 0x7f, 0x92, 0xb2, 0x2e, 0xb8, 0xfb, 0x57, 0x03, 0x23, 0xe6,
	0xb2, 0x25, 0xaf, 0xc1, 0x2c, 0x92, 0x1f, 0xbc, 0xa0, 0x9a, 0x33, 0xf1, 0x66, 0xac, 0x07, 0xe4,
	0x1c, 0x8c, 0xf6, 0x50, 0x73, 0x3a, 0x71, 0x34, 0xcf, 0xbc, 0x99, 0x5c, 0x5f, 0x33, 0x85, 0x09,
	0x01, 0xa3, 0xe1, 0xb5, 0xa4, 0xba, 0xa3, 0x7b, 0x3a, 0x53, 0x35, 0xf9, 0x08, 0x73, 0x51, 0xb7,
	0xb9, 0xa8, 0x92, 0x22, 0x6b, 0x44, 0x57, 0x53, 0xc3, 0xd1, 0x3c, 0xb8, 0x7a, 0xb3, 0x1a, 0xb2,
	0x56, 0x98, 0xb3, 0x0a, 0x07, 0x49, 0x80, 0x12, 0x76, 0xec, 0xb8, 0x78, 0x07, 0xf3, 0xa3, 0x77,
	0x72, 0x09, 0x73, 0xc6, 0x7f, 0x77, 0x79, 0xc3, 0xd3, 0x4d, 0xce, 0x8b, 0x94, 0x9a, 0x6a, 0xba,
	0x63, 0xd2, 0xed, 0x60, 0xba, 0x93, 0xd9, 0x27, 0x9e, 0xa4, 0xe4, 0x12, 0xcc, 0x52, 0x66, 0xdb,
	0x54, 0xad, 0xb1, 0xb8, 0x5a, 0x3c, 0x84, 0xef, 0x90, 0x65, 0xfd, 0x23, 0x59, 0xc2, 0xb4, 0x94,
	0x59, 0xdc, 0x6f, 0x86, 0x3a, 0xfb, 0xb1, 0x0e, 0x79, 0x36, 0x0a, 0x08, 0x55, 0xda, 0xb5, 0x48,
	0x0f, 0x54, 0x77, 0x34, 0xcf, 0x62, 0x23, 0x74, 0x6f, 0xc0, 0xba, 0x5d, 0x47, 0xbc, 0xc5, 0x61,
	0xf0, 0x0b, 0x6d, 0xd0, 0xbb, 0xbc, 0x4f, 0x36, 0x18, 0x96, 0xe8, 0xed, 0xf2, 0x74, 0x5b, 0xfd,
	0x14, 0x2a, 0xc7, 0x62, 0x23, 0x74, 0xdf, 0xc3, 0x7c, 0xf0, 0xca, 0x5a, 0x54, 0x92, 0x9f, 0x30,
	0x9f, 0xc3, 0x59, 0xc3, 0x65, 0x57, 0xb4, 0xca, 0x6b, 0xb2, 0x01, 0xb9, 0x0e, 0xc6, 0x06, 0xff,
	0x89, 0x75, 0x23, 0x6c, 0x1e, 0x3c, 0xa5, 0xf9, 0xe3, 0x89, 0x87, 0x6d, 0xc7, 0x89, 0xbf, 0x03,
	0xdc, 0x15, 0xc9, 0x81, 0x37, 0x88, 0x4e, 0x74, 0x24, 0x60, 0x54, 0x49, 0xd9, 0x7f, 0xe8, 0x8c,
	0xa9, 0x1a, 0x55, 0x49, 0xc6, 0xa9, 0xae, 0x22, 0xb0, 0x24, 0x17, 0xf0, 0xbc, 0xfe, 0x25, 0x2a,
	0xbe, 0xef, 0x4a, 0x6a, 0x28, 0xe5, 0x03, 0x5e, 0x5a, 0xa0, 0x6f, 0xc2, 0x90, 0x98, 0xa0, 0x7d,
	0xb5, 0x5f, 0x2d, 0xdf, 0x82, 0xa9, 0x6e, 0x46, 0x00, 0xce, 0x6e, 0xd7, 0xf7, 0x91, 0x1f, 0xdb,
	0xcf, 0x86, 0x3a, 0xf0, 0x63, 0x5b, 0x5b, 0x7e, 0x50, 0x57, 0x57, 0x37, 0x7a, 0x09, 0x2f, 0x76,
	0x51, 0x70, 0xcf, 0xfc, 0xcf, 0x5f, 0xfc, 0x08, 0x75, 0x36, 0x58, 0x3d, 0x11, 0xdd, 0x85, 0xfb,
	0xc8, 0xb7, 0x35, 0xb2, 0x00, 0x40, 0x66, 0x1f, 0xc6, 0xdb, 0xcd, 0x37, 0x7b, 0xf2, 0x2f, 0x00,
	0x00, 0xff, 0xff, 0x52, 0xa5, 0x3d, 0x0d, 0x0d, 0x03, 0x00, 0x00,
}
